### PR TITLE
Update queue_worker.js

### PR DESCRIPTION
**Pull request by keshavsaharia**
Updated for new Firebase library (v3.0)

### CODE REVIEW

**Comment by keshavsaharia** [comment]
I signed it! Also tests failed because they are probably using v2.3. The only changes were to .key and .ref, maybe something to make them cross-compatible? I have not checked to see if .key() and .ref() still work in v3.0.

**Comment by keshavsaharia** [comment]
Used _.isFunction to enable legacy support.

**Comment by donbarthel** [comment]
I think for Firebase 3.0 support you also have to change all mentions of:
Firebase.ServerValue.TIMESTAMP
to:
Firebase.database.ServerValue.TIMESTAMP

**Comment by donbarthel** [comment]
Oh, and you'll have to do something about the package.json as well to say that Firebase v3 is OK too. 

Your code attempts to be v2 compatible as well as v3. How to say that in package.json? Maybe a better way to go is to make this update v3 compatible only.

**Comment by drtriumph** [comment]
Thanks for your input both of you, #66 takes into account the comments / ideas here

**Pull request closed without merging**
