### PR TITLE
in_progress_state confusion

### PR DESCRIPTION
**Pull request by christianalfoni**
### Code sample

Hi there,

Our team was tracking down a bug due to us defining the same `in_progress_state` name on all our workers. We did not understand what it did, but after a great explanation here: https://github.com/firebase/firebase-queue/issues/76, we suggest to open the docs to be more explicit about how this actually works :)

Thanks for a really amazing project, this has totally saved our startup!

### CODE REVIEW

**Comment by drtriumph** [comment]
Hi @christianalfoni, thanks for the pull request. I unfortunately have to insist on the CLA being signed before I can accept even a PR to the docs.

**Comment by christianalfoni** [comment]
Ah for sure... signed it now :)

**Comment by drtriumph** [comment]
Awesome, thanks for the contribution

**Comment by christianalfoni** [comment]
Happy to help :)

**Pull request merged**
